# Generated by Django 5.0.6 on 2024-05-09 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_number', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=120)),
                ('order_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='productMaster',
            fields=[
                ('sku', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('location_id', models.CharField(max_length=120)),
                ('on_hand', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='orderLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_id', models.IntegerField()),
                ('location_id', models.CharField(max_length=120)),
                ('pick_quantity', models.IntegerField()),
                ('pick_status', models.CharField(default='pending', max_length=120)),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picks.orders')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picks.productmaster')),
            ],
        ),
    ]
