# Generated by Django 5.0.6 on 2024-05-10 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-order_date']},
        ),
    ]
