# Generated by Django 5.0.6 on 2024-05-10 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0002_alter_orders_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'get_latest_by': ['-order_date']},
        ),
    ]
